# @see https://symfony.com/doc/current/reference/configuration/doctrine.html
doctrine:
    dbal:
        # dbname: '%env(resolve:DATABASE)%'
        # host: '%env(resolve:DATABASE_HOST)%'
        # port: '%env(resolve:DATABASE_PORT)%'
        # user: '%env(resolve:DATABASE_USER)%'
        # password: '%env(resolve:DATABASE_PASSWORD)%'
        # driver: pdo_mysql
        dbname: ddbb
        host: database
        port: 3306
        user: user
        password: password
        driver: pdo_mysql
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
