version: '3'

services:
  database:
    build:
      context: ./database
    env_file:
      - .env
    ports:
    - 3306:3306
    volumes:
    - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    - ./database/data:/var/lib/mysql

  php-fpm:
    build:
      context: ./php-fpm
    env_file:
      - .env
    volumes:
      - ../symfony:/var/www/symfony
      - ./php-fpm/conf.d/:/usr/local/etc/php/conf.d
    depends_on:
      - database

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../symfony:/var/www/symfony
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php-fpm